### ISSUE TITLE
Djsjssj

### ISSUE THREAD

**Issue by Wesleyjor6** [IamRifki/IamRifki.github.io#3]
Hello I wanted to ask you, what is your prejudice with Android devices Are you afraid of them one day to spend the computer listening to the mind Of course it will never happen purely true, but could you do me a favor?  ******** and another one didn't even ask for your opinion ****, got it?  Go to the son of a bitch guy's house

**Comment by IamRifki** [comment]
What, I use Android. Bro, I was joking around, no need to take it seriously lah.

**Comment by Wesleyjor6** [comment]
oops friend it was bad I apologize
